### PR TITLE
Clang format

### PR DESCRIPTION
**Pull request by feliwir**
- add a clang-format file
- apply clang-format file
- add CI check to keep style inplace

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
The Lugaru one was based on regularizing the code style that the codebase already used, and I imagine that this one probably is more similar in style to Lugaru's code.

**Comment by feliwir** [comment]
Well, i don't really mind which one we use. However i noticed that the `.clang-format` you linked does sort the includes.
I've applied the style and end up with a compilation failure. Of course this shouldn't be the case, but the code as it currently is can't handle that.

**Comment by autious** [comment]
There was a style change some time back at wolfire, where we stopped doing newlines before opening curly on if-statements, functions classes, etc.

So

```void f() {
}```

instead of 

```void f()
{
}```

**Comment by feliwir** [comment]
Yes, that's what i thought aswell - this matches more the google style i had at first

**Review by autious — APPROVED** [review]

**Pull request merged**
